version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.23
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwe1212!Q
    volumes:
      - ./mysql-init-files/:/docker-entrypoint-initdb.d/
    command: [ 'mysqld',
               '--character-set-server=utf8mb4','--collation-server=utf8mb4_unicode_ci','--skip-character-set-client-handshake' ]
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379