server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    com.idus: DEBUG

datasource:
  write:
    url: jdbc:mysql://localhost:3306/idus_market_write?ServerTimezone=Asia/Seoul
    username: sypark
    password: qwe1212!Q
  read:
    url: jdbc:mysql://localhost:3306/idus_market_read?ServerTimezone=Asia/Seoul
    username: sypark
    password: qwe1212!Q

spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  redis:
    host: localhost
    port: 6379
